"""The container vocabulary the published specifications declare.

⚠️ **MACHINE-GENERATED. DO NOT HAND-EDIT.** Regenerate it with
``scripts/derive_specified_containers.py`` over artifacts matching the digests
below, and see the derivation note in ``docs`` for where each one comes from.

This module is DATA, not behaviour: nothing in the guard imports it, and the
scan does not change if it is deleted. It is the **checklist** -- the frozen
enumeration issue #4's exit condition is stated against -- while the weighting
lives in the guard's own vocabulary table. A test binds the two, which is what
makes "every row has a weight and a test" finite and checkable rather than a
promise about an unbounded format.

⚠️ **No fetch date is recorded here.** Verification is re-fetch, compare
digest, re-run, and diff against this file; a timestamp would make every such
run differ from the file it is checking. Dates belong to the note.
"""

from __future__ import annotations

SOURCE_DIGESTS: tuple[tuple[str, str], ...] = (
    ("gramps-xml-dtd", "98a4763424fe53947bc589780b643e5e75b15c46f92e6e1228025c8d51e9c628"),
    ("html-element-index", "373ca0a2459147bc9784d362d7437848e6bebdd4a61ad36eabf24748b11ff77c"),
    ("svg-element-index", "cdf201e0a6588896b7b1bae739ac80f7bbd44f25a2a76632a2f6762f94d02744"),
)
"""Each source artifact and the SHA-256 it was read from."""

SPECIFIED_ELEMENTS: tuple[tuple[str, str], ...] = (
    ("database", "children"),
    ("header", "children"),
    ("created", "empty"),
    ("researcher", "children"),
    ("resname", "pcdata"),
    ("resaddr", "pcdata"),
    ("reslocality", "pcdata"),
    ("rescity", "pcdata"),
    ("resstate", "pcdata"),
    ("rescountry", "pcdata"),
    ("respostal", "pcdata"),
    ("resphone", "pcdata"),
    ("resemail", "pcdata"),
    ("mediapath", "pcdata"),
    ("people", "children"),
    ("person", "children"),
    ("gender", "pcdata"),
    ("name", "children"),
    ("first", "pcdata"),
    ("call", "pcdata"),
    ("suffix", "pcdata"),
    ("title", "pcdata"),
    ("nick", "pcdata"),
    ("familynick", "pcdata"),
    ("group", "pcdata"),
    ("surname", "pcdata"),
    ("childof", "empty"),
    ("parentin", "empty"),
    ("personref", "children"),
    ("address", "children"),
    ("street", "pcdata"),
    ("locality", "pcdata"),
    ("city", "pcdata"),
    ("county", "pcdata"),
    ("state", "pcdata"),
    ("country", "pcdata"),
    ("postal", "pcdata"),
    ("phone", "pcdata"),
    ("families", "children"),
    ("family", "children"),
    ("father", "empty"),
    ("mother", "empty"),
    ("childref", "children"),
    ("type", "pcdata"),
    ("rel", "empty"),
    ("events", "children"),
    ("event", "children"),
    ("sources", "children"),
    ("source", "children"),
    ("stitle", "pcdata"),
    ("sauthor", "pcdata"),
    ("spubinfo", "pcdata"),
    ("sabbrev", "pcdata"),
    ("places", "children"),
    ("placeobj", "children"),
    ("pname", "children"),
    ("ptitle", "pcdata"),
    ("code", "pcdata"),
    ("coord", "empty"),
    ("location", "empty"),
    ("objects", "children"),
    ("object", "children"),
    ("file", "empty"),
    ("repositories", "children"),
    ("repository", "children"),
    ("rname", "pcdata"),
    ("notes", "children"),
    ("note", "children"),
    ("text", "pcdata"),
    ("style", "children"),
    ("range", "empty"),
    ("tags", "children"),
    ("tag", "empty"),
    ("citations", "children"),
    ("citation", "children"),
    ("bookmarks", "children"),
    ("bookmark", "empty"),
    ("namemaps", "children"),
    ("map", "empty"),
    ("name-formats", "children"),
    ("format", "empty"),
    ("daterange", "empty"),
    ("datespan", "empty"),
    ("dateval", "empty"),
    ("datestr", "empty"),
    ("citationref", "empty"),
    ("sourceref", "empty"),
    ("eventref", "children"),
    ("reporef", "children"),
    ("noteref", "empty"),
    ("tagref", "empty"),
    ("page", "pcdata"),
    ("confidence", "pcdata"),
    ("attribute", "children"),
    ("srcattribute", "empty"),
    ("place", "empty"),
    ("cause", "pcdata"),
    ("description", "pcdata"),
    ("url", "empty"),
    ("objref", "children"),
    ("placeref", "children"),
    ("region", "empty"),
    ("data_item", "empty"),
    ("lds_ord", "children"),
    ("temple", "empty"),
    ("status", "empty"),
    ("sealed_to", "empty"),
)
"""Every declared element, with the content model the schema gives it."""

SPECIFIED_ATTRIBUTES: tuple[tuple[str, str, str], ...] = (
    ("database", "xmlns", "CDATA"),
    ("created", "date", "CDATA"),
    ("created", "version", "CDATA"),
    ("people", "default", "CDATA"),
    ("people", "home", "IDREF"),
    ("person", "id", "CDATA"),
    ("person", "handle", "ID"),
    ("person", "priv", "enumeration"),
    ("person", "change", "CDATA"),
    ("name", "alt", "enumeration"),
    ("name", "type", "CDATA"),
    ("name", "priv", "enumeration"),
    ("name", "sort", "CDATA"),
    ("name", "display", "CDATA"),
    ("surname", "prefix", "CDATA"),
    ("surname", "prim", "enumeration"),
    ("surname", "derivation", "CDATA"),
    ("surname", "connector", "CDATA"),
    ("childof", "hlink", "IDREF"),
    ("parentin", "hlink", "IDREF"),
    ("personref", "hlink", "IDREF"),
    ("personref", "priv", "enumeration"),
    ("personref", "rel", "CDATA"),
    ("address", "priv", "enumeration"),
    ("family", "id", "CDATA"),
    ("family", "handle", "ID"),
    ("family", "priv", "enumeration"),
    ("family", "change", "CDATA"),
    ("father", "hlink", "IDREF"),
    ("mother", "hlink", "IDREF"),
    ("childref", "hlink", "IDREF"),
    ("childref", "priv", "enumeration"),
    ("childref", "mrel", "CDATA"),
    ("childref", "frel", "CDATA"),
    ("rel", "type", "CDATA"),
    ("event", "id", "CDATA"),
    ("event", "handle", "ID"),
    ("event", "priv", "enumeration"),
    ("event", "change", "CDATA"),
    ("source", "id", "CDATA"),
    ("source", "handle", "ID"),
    ("source", "priv", "enumeration"),
    ("source", "change", "CDATA"),
    ("placeobj", "id", "CDATA"),
    ("placeobj", "handle", "ID"),
    ("placeobj", "priv", "enumeration"),
    ("placeobj", "change", "CDATA"),
    ("placeobj", "type", "CDATA"),
    ("pname", "lang", "CDATA"),
    ("pname", "value", "CDATA"),
    ("coord", "long", "CDATA"),
    ("coord", "lat", "CDATA"),
    ("location", "street", "CDATA"),
    ("location", "locality", "CDATA"),
    ("location", "city", "CDATA"),
    ("location", "parish", "CDATA"),
    ("location", "county", "CDATA"),
    ("location", "state", "CDATA"),
    ("location", "country", "CDATA"),
    ("location", "postal", "CDATA"),
    ("location", "phone", "CDATA"),
    ("object", "id", "CDATA"),
    ("object", "handle", "ID"),
    ("object", "priv", "enumeration"),
    ("object", "change", "CDATA"),
    ("file", "src", "CDATA"),
    ("file", "mime", "CDATA"),
    ("file", "checksum", "CDATA"),
    ("file", "description", "CDATA"),
    ("repository", "id", "CDATA"),
    ("repository", "handle", "ID"),
    ("repository", "priv", "enumeration"),
    ("repository", "change", "CDATA"),
    ("note", "id", "CDATA"),
    ("note", "handle", "ID"),
    ("note", "priv", "enumeration"),
    ("note", "change", "CDATA"),
    ("note", "format", "enumeration"),
    ("note", "type", "CDATA"),
    ("style", "name", "enumeration"),
    ("style", "value", "CDATA"),
    ("range", "start", "CDATA"),
    ("range", "end", "CDATA"),
    ("tag", "handle", "ID"),
    ("tag", "name", "CDATA"),
    ("tag", "color", "CDATA"),
    ("tag", "priority", "CDATA"),
    ("tag", "change", "CDATA"),
    ("citation", "id", "CDATA"),
    ("citation", "handle", "ID"),
    ("citation", "priv", "enumeration"),
    ("citation", "change", "CDATA"),
    ("bookmark", "target", "enumeration"),
    ("bookmark", "hlink", "IDREF"),
    ("map", "type", "CDATA"),
    ("map", "key", "CDATA"),
    ("map", "value", "CDATA"),
    ("format", "number", "CDATA"),
    ("format", "name", "CDATA"),
    ("format", "fmt_str", "CDATA"),
    ("format", "active", "enumeration"),
    ("daterange", "start", "CDATA"),
    ("daterange", "stop", "CDATA"),
    ("daterange", "quality", "enumeration"),
    ("daterange", "cformat", "CDATA"),
    ("daterange", "dualdated", "enumeration"),
    ("daterange", "newyear", "CDATA"),
    ("datespan", "start", "CDATA"),
    ("datespan", "stop", "CDATA"),
    ("datespan", "quality", "enumeration"),
    ("datespan", "cformat", "CDATA"),
    ("datespan", "dualdated", "enumeration"),
    ("datespan", "newyear", "CDATA"),
    ("dateval", "val", "CDATA"),
    ("dateval", "type", "enumeration"),
    ("dateval", "quality", "enumeration"),
    ("dateval", "cformat", "CDATA"),
    ("dateval", "dualdated", "enumeration"),
    ("dateval", "newyear", "CDATA"),
    ("datestr", "val", "CDATA"),
    ("citationref", "hlink", "IDREF"),
    ("sourceref", "hlink", "IDREF"),
    ("eventref", "hlink", "IDREF"),
    ("eventref", "priv", "enumeration"),
    ("eventref", "role", "CDATA"),
    ("reporef", "hlink", "IDREF"),
    ("reporef", "priv", "enumeration"),
    ("reporef", "callno", "CDATA"),
    ("reporef", "medium", "CDATA"),
    ("noteref", "hlink", "IDREF"),
    ("tagref", "hlink", "IDREF"),
    ("attribute", "priv", "enumeration"),
    ("attribute", "type", "CDATA"),
    ("attribute", "value", "CDATA"),
    ("srcattribute", "priv", "enumeration"),
    ("srcattribute", "type", "CDATA"),
    ("srcattribute", "value", "CDATA"),
    ("place", "hlink", "IDREF"),
    ("url", "priv", "enumeration"),
    ("url", "type", "CDATA"),
    ("url", "href", "CDATA"),
    ("url", "description", "CDATA"),
    ("objref", "hlink", "IDREF"),
    ("objref", "priv", "enumeration"),
    ("placeref", "hlink", "IDREF"),
    ("region", "corner1_x", "CDATA"),
    ("region", "corner1_y", "CDATA"),
    ("region", "corner2_x", "CDATA"),
    ("region", "corner2_y", "CDATA"),
    ("data_item", "key", "CDATA"),
    ("data_item", "value", "CDATA"),
    ("lds_ord", "priv", "enumeration"),
    ("lds_ord", "type", "CDATA"),
    ("temple", "val", "CDATA"),
    ("status", "val", "CDATA"),
    ("sealed_to", "hlink", "IDREF"),
)
"""Every (element, attribute, declared type) the schema declares."""

MARKUP_ELEMENT_NAMES: frozenset[str] = frozenset(
    (
        "a",
        "abbr",
        "address",
        "animate",
        "animatemotion",
        "animatetransform",
        "area",
        "article",
        "aside",
        "audio",
        "b",
        "base",
        "bdi",
        "bdo",
        "blockquote",
        "body",
        "br",
        "button",
        "canvas",
        "caption",
        "circle",
        "cite",
        "clippath",
        "code",
        "col",
        "colgroup",
        "data",
        "datalist",
        "dd",
        "defs",
        "del",
        "desc",
        "details",
        "dfn",
        "dialog",
        "discard",
        "div",
        "dl",
        "dt",
        "ellipse",
        "em",
        "embed",
        "feblend",
        "fecolormatrix",
        "fecomponenttransfer",
        "fecomposite",
        "feconvolvematrix",
        "fediffuselighting",
        "fedisplacementmap",
        "fedistantlight",
        "fedropshadow",
        "feflood",
        "fefunca",
        "fefuncb",
        "fefuncg",
        "fefuncr",
        "fegaussianblur",
        "feimage",
        "femerge",
        "femergenode",
        "femorphology",
        "feoffset",
        "fepointlight",
        "fespecularlighting",
        "fespotlight",
        "fetile",
        "feturbulence",
        "fieldset",
        "figcaption",
        "figure",
        "filter",
        "footer",
        "foreignobject",
        "form",
        "g",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "head",
        "header",
        "hgroup",
        "hr",
        "html",
        "i",
        "iframe",
        "image",
        "img",
        "input",
        "ins",
        "kbd",
        "label",
        "legend",
        "li",
        "line",
        "lineargradient",
        "link",
        "main",
        "map",
        "mark",
        "marker",
        "mask",
        "menu",
        "meta",
        "metadata",
        "meter",
        "mpath",
        "nav",
        "noscript",
        "object",
        "ol",
        "optgroup",
        "option",
        "output",
        "p",
        "path",
        "pattern",
        "picture",
        "polygon",
        "polyline",
        "pre",
        "progress",
        "q",
        "radialgradient",
        "rect",
        "rp",
        "rt",
        "ruby",
        "s",
        "samp",
        "script",
        "search",
        "section",
        "select",
        "selectedcontent",
        "set",
        "slot",
        "small",
        "source",
        "span",
        "stop",
        "strong",
        "style",
        "sub",
        "summary",
        "sup",
        "svg",
        "switch",
        "symbol",
        "table",
        "tbody",
        "td",
        "template",
        "text",
        "textarea",
        "textpath",
        "tfoot",
        "th",
        "thead",
        "time",
        "title",
        "tr",
        "track",
        "tspan",
        "u",
        "ul",
        "unknown",
        "use",
        "var",
        "video",
        "view",
        "wbr",
    )
)
"""Every element name the two published markup indexes list."""
