"""What an approval render may put on screen, and the refusal when it may not.

⛔ **This is the write surface's last check on the text a person agrees to.**
``host.document.preview`` renders the one sentence a person reads and approves
before anything is written to a tree; this module says which characters that
sentence may not carry, and refuses the whole render when one arrives.

⚠️ **The class is a committed derived table**, ``core/_unrenderable.py``,
generated by ``scripts/derive_unrenderable.py`` from two artifacts of one
published Unicode release. Nothing here asks the running interpreter anything.

⭐ **Moved here from ``core/schema.py``, which was retired with the note flow.**
The guard was written for that flow's renderer and was left uncalled and
untested by the retirement. What moved is the class, the lookup and the
rationale below; what did not move is the fragment-level attribution, which
depended on the operation model's ``Fragment`` and has no counterpart on the
document route -- see ``refuse_unrenderable``.
"""

from __future__ import annotations

import bisect
from collections.abc import Sequence

from gramps_live_api.core._unrenderable import UNRENDERABLE_RANGES

# ---------------------------------------------------------------------------
# What an approval render may put on screen
#
# ``host.document.preview`` renders the one sentence a person reads and approves
# BEFORE anything is written to a tree, which is this project's whole review
# model: what was agreed and what is written are provably the same thing. A
# character that REORDERS, HIDES or FORGES part of that sentence -- a
# bidirectional override, a zero-width character, a line separator -- attacks the
# agreement step itself, because the reviewer approves one sentence and a
# different one is what the graph says.
#
# ⚠️ **The guard is over what the renderer EMITS, not over what any field may
# hold.** It reads the rendered sentence, so every rendered field is covered at
# once and a field added to the renderer later is covered without this being
# edited. The alternative -- a character rule per field at validation or
# acceptance time -- was weighed and rejected: nothing here can establish what
# characters Gramps emits in an opaque identifier, and a rendering guard does not
# need to. It constrains what we DISPLAY, not what we accept.
#
# ⛔ **That rejection was re-affirmed by the owner when this moved.** The plan
# for the move carried a second wiring point at ``propose_document``, over an
# UNRESOLVED render, and it was removed: with no resolution every attachable
# node is classified as being created, so its payload renders and a gate there
# refuses characters in fields the approval render drops. The cost is concrete
# and is named further down -- this class refuses ideographic variation
# selectors, which is how a genealogical source spells some surnames -- so the
# removed gate would have refused a name in a field nobody would ever have seen.
#
# ---------------------------------------------------------------------------
# What this costs, and what it does not reach. Recorded rather than carved
# around, because each of these is a residual somebody should meet here instead
# of discovering it.
#
# ⚠️ **The class refuses characters some scripts need.** The zero-width
# non-joiner and joiner (U+200C, U+200D) are required by Persian and Indic
# text, and they are the same general category as the ones that hide a sentence
# from its reader. **So a legitimate note in those scripts becomes
# unpreviewable, and therefore unapprovable.** That is a real cost and it is
# taken as a stated trade: no published definition separates
# invisible-and-dangerous from invisible-and-legitimate, because the same
# characters are both. Carving the joiners out by hand would be the enumeration
# pointed backwards -- a known-safe list, failing by admitting whatever nobody
# carved. If this ever needs narrowing it needs a ruling with evidence, not an
# exemption added here.
#
# ⭐ **That cost is WIDER since the class became the union with
# Default_Ignorable_Code_Point, and the extra characters are ordinary script
# data, not formatting.** Refused now, and every one of them is used
# legitimately:
#
#   - the **Mongolian free variation selectors** (U+180B-U+180D, U+180F), which
#     select the positional form of a Mongolian letter;
#   - the **variation selectors** (U+FE00-U+FE0F, U+E0100-U+E01EF), which are
#     how an ideographic variation sequence names one of several published
#     glyphs for a Han character -- exactly the kind of thing a genealogical
#     source spells a surname with;
#   - the **Hangul fillers** (U+115F, U+1160, U+3164, U+FFA0), which stand in
#     for an absent jamo in an incomplete syllable;
#   - the **combining grapheme joiner** (U+034F) and the Khmer vowel inherent
#     signs (U+17B4-U+17B5).
#
# **This is a real cost to legitimate script data and it is not negligible.**
# The trade is taken deliberately and on one ground: in a *rendered identifier*
# an invisible character is precisely the risk this guard exists for. A
# reviewer approves a sentence they can read, and a character that occupies no
# space is one the sentence does not show them -- whatever role it plays in a
# font. A reader who needs this reversed should find the reasoning here rather
# than a shrug: it needs a ruling with evidence, and the evidence would be
# about which of these can appear in a Gramps identifier or a note that a
# person still has to check against a record.
#
# ⚠️ **Truncation is no longer a residual here at all, and the paragraph that
# used to stand in this place is REWRITTEN rather than moved.** In the retired
# flow it read: the one-line summary elides free text, so a character past the
# limit is never emitted, and a guard over what we DISPLAY has nothing to say
# about a character that reaches no screen -- later qualified when a second,
# unelided display site appeared. **Neither half survives the move.** The
# document route elides nothing: ``host.document.WRAP_AT`` wraps and never
# truncates, because R3's ruled criterion is that no byte reaches the tree that
# was not rendered in full. There is no elision point for a character to hide
# past, so there is nothing left to qualify. It is written out rather than
# dropped in silence, because a reader who remembers the old residual should
# find out here that it was retired and why, not conclude it was forgotten.
#
# ⚠️ **Whitespace control characters are refused where the renderer emits them
# RAW, and never reach this guard where it wraps.** This is new with the move
# and it is the seam's shape rather than a decision taken twice. The retired
# flow collapsed a fragment's whitespace before scanning it, so a tab could
# never be refused; ``host.document.preview`` has no whole-sentence collapse.
# What it has instead is ``_wrap``, and ``textwrap`` replaces ``\t``, ``\r``,
# ``\x0b`` and ``\x0c`` with spaces and splits on ``\n`` before a line is ever
# appended -- so wrapped text, which is every note body, reaches this guard with
# no whitespace control in it. A field the renderer interpolates into a raw
# f-string -- a person's given name, a place title -- does not go through that,
# and a control character there arrives here and is refused as the ``Cc`` it is.
# **Both directions are deliberate and both are pinned by tests:**
#
#   - a payload U+000A in a person's ``given`` is refused, which is the same
#     line-forgery a raw f-string would otherwise let a payload assemble;
#   - a tab in that same field is refused too, and that is the cost -- fail
#     closed, on a character no genealogical identifier needs.
#
# ⭐ **The class now names ``Zl`` and ``Zp`` as well, and that is the COMPLETION
# of the property above rather than a new one arriving.** U+2028 and U+2029 are
# the Unicode line and paragraph separators; a text view breaks a line on either,
# so a payload carrying one in a person's ``given`` forged a second line of the
# approval dialog reading as a record the graph never named -- measured on both
# code points, and the identical forgery ``Cc`` has always been refused for. The
# class has never meant "invisible": it holds ``Cc``, which is where U+000A and
# U+0009 live, neither of them invisible and both of them structural. It has
# always refused characters that forge the structure of a sentence somebody is
# being asked to approve, and these two were the separators the General_Category
# group "Other" does not reach. **This closes a bypass of a refusal that already
# existed.** Measured cost of saying so: two rows and two code points, 40 to 42
# and 143,787 to 143,789.
#
#   - ⚠️ **And they reach this guard on BOTH routes, which the paragraph above
#     does not cover.** ``textwrap``'s replacement set is the whitespace
#     CONTROLS, and does not include either separator -- so unlike a tab, a
#     separator in a note body survives the wrap and is refused there too. That
#     is deliberate and it is the cost here: a note pasted from an editor that
#     spells a soft line break U+2028, where the same note spelled with U+000A
#     wraps and previews cleanly, becomes unapprovable until the character is
#     removed. It is the same trade #236 records for the tab, taken on the same
#     ground -- the two routes cannot be exempted separately without exempting
#     the forgery -- and it is written down here rather than discovered.
#
# ⚠️ **Implicit reordering is not covered, and must not be.** A strong
# right-to-left letter -- an ordinary name, category Lo -- reorders the neutral
# characters around it under UAX #9 with no formatting character present at
# all, and it is nowhere near this class. Covering it would mean refusing
# legitimate names, in a genealogy tool. That mitigation belongs to whatever
# eventually displays the sentence, which can isolate each field; it is not
# available to a function that returns a string.
#
# ⚠️ **The class no longer depends on the interpreter, and what it costs
# instead is a PIN.** The verdict used to move between the Unicode databases
# CPython bundles -- 139,742 / 139,744 / 139,751 code points on 3.10 / 3.11 /
# 3.12, nine of them flipping, with the older interpreter the permissive side.
# It is now a committed derived table (``_unrenderable.py``, generated by
# ``scripts/derive_unrenderable.py``, provenance in
# ``docs/schema-render-guard-derivation.md``): 143,789 code points, identical
# on all three, measured rather than argued. The two prices of that:
#
#   - **The table is pinned NEWER than any interpreter here bundles**, at
#     Unicode 17.0.0 against UCD 13.0.0 / 14.0.0 / 15.0.0. So the guard refuses
#     code points the running interpreter calls unassigned -- **3,779 / 3,776 /
#     3,769** of them respectively. That is deliberate and it is fail-closed:
#     the standard has assigned them, and a display stack newer than the
#     service will act on them. It is the direction the old residual could not
#     choose, because the old class had no version of its own.
#   - **The class is a fact about ONE release and does not track a later one
#     until somebody re-derives it.** That is the mirror image of the residual
#     this replaces: determinism bought with staleness. A character assigned
#     after 17.0.0 is emitted until the table is regenerated -- a fail-OPEN,
#     bounded by the standard's release cadence and visible in a diff, which
#     the old dependence was neither. Re-derivation is one command over two
#     artifacts and it is written down.
#
# **Both deterministic alternatives were still weighed and rejected, and this
# stays so the next reader does not reach for them.** Pinning an explicit set
# of format characters *here* is the enumeration this project refuses
# everywhere else -- it fails open on whatever the standard assigns next, with
# nothing to re-derive. Inverting to a safe-to-display set is that enumeration
# pointed backwards, failing closed on legitimate text nobody listed. **A
# derived table is neither**: what it enumerates is a published property at a
# named version, so it fails open only until it is regenerated, and the
# regeneration is mechanical.
# ---------------------------------------------------------------------------

_RANGE_STARTS: tuple[int, ...] = tuple(first for first, _, _ in UNRENDERABLE_RANGES)
"""Where each committed range begins, for the lookup below.

Derived from the table rather than written beside it, so the two cannot drift.
A frozenset of the ~143,700 code points was rejected on memory grounds; a
bisect over the committed rows answers in ``O(log n)``.

⚠️ **The row count is deliberately not written here.** It said 41 while the table
held 40: the neighbouring code-point figure was updated when the guard moved and the row
count was carried over stale, which is how a documented count goes wrong without anything
announcing it. The number belongs to ``_unrenderable.py``, moves whenever the derivation is
re-run, and is checkable there by anyone who needs it.
"""


def class_of(character: str) -> str | None:
    """Which published fact puts ``character`` in the class, or ``None``.

    **The class is a committed derived table, not a question put to the running
    interpreter.** ``_unrenderable.py`` is generated by
    ``scripts/derive_unrenderable.py`` from two artifacts of one published
    Unicode release, whose digests the module carries and whose provenance is
    in ``docs/schema-render-guard-derivation.md``. The verdict is therefore a
    fact about the standard, and the same graph previews the same way on every
    interpreter this project supports -- measured, not assumed.

    ⚠️ **Public, where it was ``_class_of``, because its consumer now lives in
    another package.** ``host.document`` imports this module; a leading
    underscore reached across a package boundary would be the convention saying
    one thing and every call site saying another.

    **The class is the UNION of two published facts**, because neither contains
    the other:

    - the General_Category values ``Cc``, ``Cf``, ``Co``, ``Cs``, ``Zl`` and
      ``Zp`` of UAX #44, where the explicit directional formatting characters of
      the Bidirectional Algorithm (UAX #9) live, along with the zero-width
      characters, the controls, the surrogates, the private-use areas and the two
      separators a text view breaks a line on;
    - the derived core property ``Default_Ignorable_Code_Point``, which reaches
      **outside** those categories -- U+034F is ``Mn``, U+115F and U+1160 are ``Lo``,
      and all three render as nothing at all.

    A class written as the categories alone emitted every one of those; a class
    written as the property alone would emit the controls and the surrogates.

    ⚠️ **``Zs`` is NOT among them and must not be added.** The ordinary space is
    the one separator that renders as itself and forges nothing, and the class
    is what the six named categories select rather than the ``Z`` group.

    ⚠️ **``Cn`` is absent because nothing selects it, not because a clause
    excludes it.** Unassigned code points ARE stated explicitly in the
    general-category artifact; the derivation names the six categories it
    wants, so unassigned and every readable category are left out by the same
    structure. There is no ``!= "Cn"`` anywhere to get wrong.

    ⚠️ **Do not add a case here, and do not hand-edit the table.** A character
    this guard should refuse and does not is a re-derivation against a newer
    release, or a defect in the derivation script -- both of which are visible
    in a diff. A case added by hand is the enumeration this project refuses
    everywhere else, and it would make the committed table stop being the class.

    Returns the label the table carries, which is what the refusal names, so a
    caller never has to ask a second source what it just refused.
    """
    code_point = ord(character)
    position = bisect.bisect_right(_RANGE_STARTS, code_point) - 1
    if position < 0:
        return None
    _, last, label = UNRENDERABLE_RANGES[position]
    return label if code_point <= last else None


class UnrenderableTextError(Exception):
    """An approval render that cannot be put in front of a reviewer as it stands.

    ⚠️ **The message names the published fact that refused the character, and
    never the character, the field or any payload value.** A payload echoed into
    an error becomes content this repository then has to scan, and any caller
    that logs the failure would be what published it -- the plugin's catch-all
    puts a traceback in a dialog, so this message reaches a screen.

    ⚠️ **It names NO field, and that is a loss taken deliberately rather than an
    omission.** The retired flow's ``UnrenderableFieldError`` carried a field
    path, read off the fragment that produced the character. ``preview`` has no
    per-fragment provenance -- it appends finished lines to a list -- so a field
    path here could only come from searching the graph for the character
    afterwards, which cannot tell two rendered fields carrying the same
    character apart and answers by declaration order. **A refusal naming the
    wrong field is worse than one naming none**, because its correction leaves
    the refusal standing. The class is named instead, which is what a reader
    looks up.

    ⚠️ **``label`` is read off the committed table and is not a call to the
    running interpreter.** Under a pinned table ``unicodedata.category`` would
    report ``Cn`` for a code point the table guards as ``Cf`` -- a refusal naming
    the one category the class does not hold. So the value is a General_Category
    value or ``Default_Ignorable_Code_Point``: it keeps its meaning and gains one
    value that is not a category, because one half of the class is not one.

    ⚠️ **``Exception`` and deliberately not ``ValueError``.** ``GraphInvalid`` is
    a ``ValueError`` and it means *the caller sent something unusable*; this
    means *a valid graph produced text nobody may be asked to approve*. Sharing
    a base would let an ``except ValueError`` written for the first silently
    swallow the second, on the one surface where failing closed is the point.
    """

    def __init__(self, label: str) -> None:
        super().__init__(
            f"the approval text carries a {label} character, which can reorder "
            "or hide text in a sentence for review, so it cannot be shown for "
            "approval and nothing was written"
        )
        self.label = label


def refuse_unrenderable(lines: Sequence[str]) -> None:
    """Refuse the render if any line carries a character that reorders or hides it.

    ⛔ **Every character of every line, with nothing skipped.** No carve-out for
    whitespace, for the renderer's own punctuation, or for text the renderer
    believes it wrote itself. A guard with an exemption is a guard whose
    exemption is the attack.

    ⭐ **PER LINE, which is what makes a payload newline a refusal.** The caller
    holds the assembled lines and joins them with ``"\\n"`` afterwards, so a
    U+000A inside one of them is a payload character and not structure: it would
    forge an extra line in the approval dialog, reading as a record the graph
    never named. Scanning the joined string instead would have to permit U+000A
    everywhere and lose exactly that case.

    ⚠️ **The caller must call this on the lines BEFORE joining them**, for the
    same reason. A call site that joins first has quietly changed what the guard
    can see.

    Deterministic in both directions: the first line in the order a person READS
    the render, and the first offending character within it.
    """
    for line in lines:
        for character in line:
            label = class_of(character)
            if label is not None:
                raise UnrenderableTextError(label)
